### ISSUE TITLE
Remove aws_s3_bucket_acl resource when private

### ISSUE THREAD

**Issue by angelosleebos** [joshuamkite/terraform-aws-static-website-s3-cloudfront-acm#3]
Please remove aws s3 bucket acl as for april 2023 all s3 buckets are set private as default.  

`resource "aws_s3_bucket_acl" "this" {
  bucket = aws_s3_bucket.this.id
  acl    = "private"
}`

**Comment by joshuamkite** [comment]
[Fixed](https://github.com/joshuamkite/terraform-aws-static-website-s3-cloudfront-acm/releases/tag/2.2.0). Thanks for pointing this out.
